Uncomment files

diff --git a/kubernetes/cray-bos/templates/post-upgrade-job.yaml b/kubernetes/cray-bos/templates/post-upgrade-job.yaml
--- a/kubernetes/cray-bos/templates/post-upgrade-job.yaml
+++ b/kubernetes/cray-bos/templates/post-upgrade-job.yaml
@@ -22,85 +22,85 @@ ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 OTHER DEALINGS IN THE SOFTWARE.
 */}}
 
-#---
-#apiVersion: batch/v1
-#kind: Job
-#metadata:
-#  name:  "{{ include "cray-service.name" . }}-migration"
-#  labels:
-#    app.kubernetes.io/managed-by: "{{ include "cray-service.name" . }}"
-#    app.kubernetes.io/instance: "{{ include "cray-service.name" . }}"
-#    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
-#    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
-#  annotations:
-#    "helm.sh/hook": post-upgrade
-#    "helm.sh/hook-weight": "-1"
-#    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
-#
-#
-#spec:
-#  template:
-#    metadata:
-#      name: "{{ .Release.Name }}"
-#      labels:
-#        app.kubernetes.io/managed-by:  "{{ include "cray-service.name" . }}"
-#        app.kubernetes.io/instance:  "{{ include "cray-service.name" . }}"
-#        app.kubernetes.io/name:  "{{ include "cray-service.name" . }}-migration"
-#        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
-#      annotations:
-#        traffic.sidecar.istio.io/excludeOutboundPorts: "2379,2380,6379"
-#        "proxy.istio.io/config": '{ "holdApplicationUntilProxyStarts": true }'
-#    spec:
-#      serviceAccountName: "{{ include "cray-service.name" . }}-migration"
-#      restartPolicy: Never
-#      securityContext:
-#        runAsNonRoot: true
-#        runAsUser: 65534
-#        runAsGroup: 65534
-#
-#      initContainers:
-#      - name: cray-bos-wait-for-etcd
-#        image: artifactory.algol60.net/csm-docker/stable/docker-kubectl:1.19.15
-#        command:
-#          - /bin/sh
-#          - -c
-#          - |
-#            while true; do
-#              JOB_CONDITION="$(kubectl get jobs -n services -l app.kubernetes.io/name=cray-bos-wait-for-etcd -o jsonpath='{.items[0].status.conditions[0].type}')"
-#              JOB_CONDITION_RC=$?
-#              if [ $JOB_CONDITION_RC -eq 0 ]; then
-#                if [ "$JOB_CONDITION" == 'Complete' ]; then
-#                  echo "Completed"
-#                  break
-#                fi
-#                echo "Waiting for the cray-bos-wait-for-etcd job in the services namespace to complete, current condition is $(kubectl get jobs -n services -l app.kubernetes.io/name=cray-bos-wait-for-etcd -o jsonpath='{.items[0].status}')"
-#                sleep 3
-#              elif [ $JOB_CONDITION_RC -ne 1 ]; then
-#                echo "'kubectl get jobs' failed with exit code $JOB_CONDITION_RC , failing"
-#                exit 1
-#              else
-#                echo "'kubectl get jobs' failed with exit code $JOB_CONDITION_RC , will retry"
-#              sleep 3
-#              fi
-#            done
-#      containers:
-#      - name: bos-migrations
-#        image: {{ index .Values "cray-service" "containers" "cray-bos" "image" "repository" }}:{{ .Chart.AppVersion}}
-#        command:
-#          - python3
-#          - "-m"
-#          - "bos.server.migrations"
-#        env:
-#        - name: APP_VERSION
-#          value: 0.0.0-app-version
-#        {{ range (index .Values "cray-service" "containers" "cray-bos" "ports") -}}
-#        {{if eq .name "http" }}
-#        - name: BOS_CONTAINER_PORT
-#          value: "{{ .containerPort }}"
-#        {{ end }}
-#        {{- end }}
-#        ports:
-#        - name: http
-#          containerPort: 9000
-#          protocol: TCP
+---
+apiVersion: batch/v1
+kind: Job
+metadata:
+  name:  "{{ include "cray-service.name" . }}-migration"
+  labels:
+    app.kubernetes.io/managed-by: "{{ include "cray-service.name" . }}"
+    app.kubernetes.io/instance: "{{ include "cray-service.name" . }}"
+    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
+    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
+  annotations:
+    "helm.sh/hook": post-upgrade
+    "helm.sh/hook-weight": "-1"
+    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
+
+
+spec:
+  template:
+    metadata:
+      name: "{{ .Release.Name }}"
+      labels:
+        app.kubernetes.io/managed-by:  "{{ include "cray-service.name" . }}"
+        app.kubernetes.io/instance:  "{{ include "cray-service.name" . }}"
+        app.kubernetes.io/name:  "{{ include "cray-service.name" . }}-migration"
+        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
+      annotations:
+        traffic.sidecar.istio.io/excludeOutboundPorts: "2379,2380,6379"
+        "proxy.istio.io/config": '{ "holdApplicationUntilProxyStarts": true }'
+    spec:
+      serviceAccountName: "{{ include "cray-service.name" . }}-migration"
+      restartPolicy: Never
+      securityContext:
+        runAsNonRoot: true
+        runAsUser: 65534
+        runAsGroup: 65534
+
+      initContainers:
+      - name: cray-bos-wait-for-etcd
+        image: artifactory.algol60.net/csm-docker/stable/docker-kubectl:1.19.15
+        command:
+          - /bin/sh
+          - -c
+          - |
+            while true; do
+              JOB_CONDITION="$(kubectl get jobs -n services -l app.kubernetes.io/name=cray-bos-wait-for-etcd -o jsonpath='{.items[0].status.conditions[0].type}')"
+              JOB_CONDITION_RC=$?
+              if [ $JOB_CONDITION_RC -eq 0 ]; then
+                if [ "$JOB_CONDITION" == 'Complete' ]; then
+                  echo "Completed"
+                  break
+                fi
+                echo "Waiting for the cray-bos-wait-for-etcd job in the services namespace to complete, current condition is $(kubectl get jobs -n services -l app.kubernetes.io/name=cray-bos-wait-for-etcd -o jsonpath='{.items[0].status}')"
+                sleep 3
+              elif [ $JOB_CONDITION_RC -ne 1 ]; then
+                echo "'kubectl get jobs' failed with exit code $JOB_CONDITION_RC , failing"
+                exit 1
+              else
+                echo "'kubectl get jobs' failed with exit code $JOB_CONDITION_RC , will retry"
+              sleep 3
+              fi
+            done
+      containers:
+      - name: bos-migrations
+        image: {{ index .Values "cray-service" "containers" "cray-bos" "image" "repository" }}:{{ .Chart.AppVersion}}
+        command:
+          - python3
+          - "-m"
+          - "bos.server.migrations"
+        env:
+        - name: APP_VERSION
+          value: 0.0.0-app-version
+        {{ range (index .Values "cray-service" "containers" "cray-bos" "ports") -}}
+        {{if eq .name "http" }}
+        - name: BOS_CONTAINER_PORT
+          value: "{{ .containerPort }}"
+        {{ end }}
+        {{- end }}
+        ports:
+        - name: http
+          containerPort: 9000
+          protocol: TCP
 
