Adding a wait-for-etcd init container to this job
I thought including the cray-service base chart would add this init
container automatically for the job, but it did not. Thus, I am adding
it manually.

diff --git a/kubernetes/cray-bos/templates/post-upgrade-job.yaml b/kubernetes/cray-bos/templates/post-upgrade-job.yaml
--- a/kubernetes/cray-bos/templates/post-upgrade-job.yaml
+++ b/kubernetes/cray-bos/templates/post-upgrade-job.yaml
@@ -24,6 +24,31 @@ spec:
         helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
     spec:
       restartPolicy: Never
+      
+      initContainers:
+      - name: cray-bos-wait-for-etcd
+        image: artifactory.algol60.net/csm-docker/stable/docker-kubectl:1.19.15
+        command:
+          /bin/sh
+          -c
+          while true; do
+            JOB_CONDITION="$(kubectl get jobs -n services -l app.kubernetes.io/name=cray-bos-wait-for-etcd -o jsonpath='{.items[0].status.conditions[0].type}')"
+            JOB_CONDITION_RC=$?
+            if [ $JOB_CONDITION_RC -eq 0 ]; then
+              if [ "$JOB_CONDITION" == 'Complete' ]; then
+                echo "Completed"
+                break
+              fi
+              echo "Waiting for the cray-bos-wait-for-etcd job in the services namespace to complete, current condition is $(kubectl get jobs -n services -l app.kubernetes.io/name=cray-bos-wait-for-etcd -o jsonpath='{.items[0].status}')"
+              sleep 3
+            elif [ $JOB_CONDITION_RC -ne 1 ]; then
+              echo "'kubectl get jobs' failed with exit code $JOB_CONDITION_RC , failing"
+              exit 1
+            else
+              echo "'kubectl get jobs' failed with exit code $JOB_CONDITION_RC , will retry"
+              sleep 3
+            fi
+          done      
       containers:
       - name: v1-v2-session-template-migration  
         image: {{ index .Values "cray-service" "containers" "cray-bos" "image" "repository" }}:{{ .Chart.AppVersion}}
